/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as TopicsIndexImport } from './routes/topics/index'
import { Route as TopicsNewImport } from './routes/topics/new'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TopicsIndexRoute = TopicsIndexImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRoute,
} as any)

const TopicsNewRoute = TopicsNewImport.update({
  id: '/topics/new',
  path: '/topics/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/topics/new': {
      id: '/topics/new'
      path: '/topics/new'
      fullPath: '/topics/new'
      preLoaderRoute: typeof TopicsNewImport
      parentRoute: typeof rootRoute
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/topics/new': typeof TopicsNewRoute
  '/topics': typeof TopicsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/topics/new': typeof TopicsNewRoute
  '/topics': typeof TopicsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/topics/new': typeof TopicsNewRoute
  '/topics/': typeof TopicsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/topics/new' | '/topics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/topics/new' | '/topics'
  id: '__root__' | '/' | '/auth' | '/topics/new' | '/topics/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  TopicsNewRoute: typeof TopicsNewRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  TopicsNewRoute: TopicsNewRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/topics/new",
        "/topics/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/topics/new": {
      "filePath": "topics/new.tsx"
    },
    "/topics/": {
      "filePath": "topics/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
